MODULES=(applespi spi_pxa2xx_platform intel_lpss_pci intel_lpss_acpi)
BINARIES=()
FILES=()
HOOKS=(base udev autodetect microcode modconf kms keyboard keymap block filesystems fsck)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-c -T0 --long -19)
