#!/usr/bin/env bash
# run-demo.sh — bring up the real MavLinOS desktop in an isolated Xvfb and
# capture presentation screenshots.
#
# WHAT RUNS: the project's real session stack — xfwm4 (Mavericks window
# decorations + compositor), xfdesktop (wallpaper), xfce4-panel (menu bar
# with the mv-apple Apple-menu plugin built from this repo), plank dock
# (Mavericks theme) — plus real mv-* applications from this checkout.
#
# ISOLATION (hard requirement — the dev host is WSLg and DISPLAY=:0 /
# WAYLAND_DISPLAY=wayland-0 leak onto the user's Windows desktop):
#   * scripts/gui-isolation.sh mv_gui_isolate — captures the ambient host
#     display(s) as FORBIDDEN, unsets WAYLAND_DISPLAY, forces GDK_BACKEND=x11,
#     arms the fail-loud sitecustomize guard (HOST-DISPLAY-BLOCKED, exit 125);
#   * the session runs on a dedicated Xvfb display (:98 by default, never the
#     host :0 and never the test-suite-pinned :97);
#   * demo-capture.py independently refuses to capture any display that
#     looks like a host display.
#
# Everything the session needs (theme, panel plugin, rofi themes, desktop
# entries) is staged into <demo-root>/prefix from THIS checkout; the demo
# HOME is generated by make-demo-home.sh. No product file is modified.
#
# Output: artifacts/demo/*.png (next to the repo checkout).
# License: GPL-2.0-or-later.
set -uo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
DEMO_ROOT="${MV_DEMO_ROOT:-/tmp/opencode/mavlinos-demo}"
DEMO_DISPLAY="${MV_DEMO_DISPLAY:-:98}"
GEOMETRY="${MV_DEMO_GEOMETRY:-1680x1050x24}"
OUT_DIR="$REPO/artifacts/demo"
SHOT_DIR="$DEMO_ROOT/shots"
LOGS="$DEMO_ROOT/logs"
BIN="$REPO/packages/mavericks-apps/src/mavericks-apps/bin"
THEME_SRC="$REPO/packages/mavericks-theme/src/mavericks-theme"
PREFIX="$DEMO_ROOT/prefix"
HOME_DIR="$DEMO_ROOT/home"
mkdir -p "$DEMO_ROOT" "$SHOT_DIR" "$LOGS" "$OUT_DIR"

log() { echo "[demo] $*"; }
die() { echo "[demo] FATAL: $*" >&2; exit 1; }

# ---------------------------------------------------------------- isolation
# shellcheck source=../gui-isolation.sh
source "$REPO/scripts/gui-isolation.sh"
mv_gui_isolate || die "cannot arm GUI isolation"
if [ -n "${DISPLAY:-}" ] && [ "$DISPLAY" != "$DEMO_DISPLAY" ]; then
    log "host display ${DISPLAY} captured as forbidden (guard armed)"
fi

# ------------------------------------------------------------ stage prefix
stage_prefix() {
    log "staging demo prefix (mavericks-apps + mavericks-theme from this checkout)"
    make -C "$REPO/packages/mavericks-apps/src/mavericks-apps" clean >/dev/null 2>&1
    make -C "$REPO/packages/mavericks-apps/src/mavericks-apps" -j4 >/dev/null 2>&1 \
        || die "mavericks-apps build failed"
    make -C "$REPO/packages/mavericks-apps/src/mavericks-apps" \
        DESTDIR="$PREFIX" PREFIX=/usr install >/dev/null 2>&1 \
        || die "mavericks-apps staging failed"

    local P="$PREFIX/usr/share" T="$THEME_SRC"
    rm -rf "$P/themes/Mavericks" "$P/icons/Mavericks" \
           "$P/icons/Mavericks-Cursors" "$P/plank/themes/Mavericks"
    mkdir -p "$P/themes/Mavericks/gtk-3.0" "$P/themes/Mavericks/gtk-3.20" \
             "$P/icons" "$P/plank/themes" "$P/backgrounds/mavericks"
    sassc -t compressed "$T/gtk-3.0/gtk.scss"  "$P/themes/Mavericks/gtk-3.0/gtk.css"  2>"$LOGS/sassc.log" \
        || die "theme SCSS (3.0) failed: $LOGS/sassc.log"
    sassc -t compressed "$T/gtk-3.20/gtk.scss" "$P/themes/Mavericks/gtk-3.20/gtk.css" 2>>"$LOGS/sassc.log" \
        || die "theme SCSS (3.20) failed: $LOGS/sassc.log"
    cp -r "$T/xfwm4" "$P/themes/Mavericks/xfwm4"
    cp -r "$T/icons/."   "$P/icons/Mavericks/"
    cp -r "$T/cursors"   "$P/icons/Mavericks-Cursors"
    cp -r "$T/plank/."   "$P/plank/themes/Mavericks/"
    cp "$T/wallpapers/mavericks-desktop.png" "$P/backgrounds/mavericks/"
}

stage_prefix

# The mv-apple panel plugin must sit in the panel's compile-time module dir
# (X-XFCE-Module lookup is not XDG_DATA_DIRS-relative in xfce4-panel 4.20).
# This dev container already carries the project's installed mv-* bits
# (docs/ENVIRONMENT.md); install the freshly built plugin there, idempotently.
if ! cmp -s packages/mavericks-apps/src/mavericks-apps/libmv-apple.so \
            /usr/lib/xfce4/panel/plugins/libmv-apple.so 2>/dev/null; then
    sudo -n install -Dm755 packages/mavericks-apps/src/mavericks-apps/libmv-apple.so \
        /usr/lib/xfce4/panel/plugins/libmv-apple.so \
        && sudo -n install -Dm644 packages/mavericks-apps/src/mavericks-apps/panel/mv-apple.desktop \
        /usr/share/xfce4/panel/plugins/mv-apple.desktop \
        || die "cannot install mv-apple panel plugin (sudo required)"
    log "mv-apple panel plugin installed to /usr"
fi
# mv-* app __main__ blocks import the shared runner from the hardcoded path
# /usr/share/mavericks-apps — keep it current with this checkout (dev host
# already carries the installed package per docs/ENVIRONMENT.md).
sudo -n cp packages/mavericks-apps/src/mavericks-apps/lib/mavericks_appmenu.py \
           packages/mavericks-apps/src/mavericks-apps/lib/mission_control_thumbnail.py \
           /usr/share/mavericks-apps/ 2>/dev/null || true
sudo -n cp packages/mavericks-apps/src/mavericks-apps/config/rofi-mavericks.rasi \
           packages/mavericks-apps/src/mavericks-apps/config/rofi-launchpad.rasi \
           packages/mavericks-apps/src/mavericks-apps/config/rofi-mission-control.rasi \
           packages/mavericks-apps/src/mavericks-apps/config/thunar-uca.xml \
           packages/mavericks-apps/src/mavericks-apps/config/xfce4-keyboard-shortcuts.xml \
           /usr/share/mavericks-apps/ 2>/dev/null || true

# --------------------------------------------------------------- demo HOME
# Home setup only edits config files — drop the ambient (host) display so
# the armed guard does not abort its python helpers; DISPLAY is re-exported
# to the dedicated Xvfb below, before anything graphical starts.
unset DISPLAY WAYLAND_DISPLAY
bash "$REPO/scripts/demo/make-demo-home.sh" "$DEMO_ROOT" "$REPO" || die "demo home failed"

# plank (dconf backend on this host) needs its prefs seeded as gsettings;
# the skel INI is the product source of truth — convert it deterministically.
seed_plank_dconf() {
    local ini="$HOME_DIR/.config/plank/dock1/settings"
    local key val S
    S="net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/"
    while IFS='=' read -r key val; do
        [ -n "$key" ] || continue
        case "$key" in
            \[*) ;;
            Theme)          gsettings set "$S" theme "'$val'" ;;
            ZoomEnabled)    gsettings set "$S" zoom-enabled "$(echo "$val" | tr 'A-Z' 'a-z')" ;;
            ZoomPercent)    gsettings set "$S" zoom-percent "$val" ;;
            IconSize)       gsettings set "$S" icon-size "$val" ;;
            HideMode)       gsettings set "$S" hide-mode "$val" ;;
            ShowDockItem)   gsettings set "$S" show-dock-item "$(echo "$val" | tr 'A-Z' 'a-z')" ;;
            Alignment)      [ "$val" = 3 ] && gsettings set "$S" alignment "'center'" || gsettings set "$S" alignment "'left'" ;;
            Position)       [ "$val" = 1 ] && gsettings set "$S" position "'bottom'" || gsettings set "$S" position "'top'" ;;
            Offset)         gsettings set "$S" offset "$val" ;;
            UrgentHueShift) gsettings set "$S" urgent-hue-shift "$val" ;;
        esac
    done < "$ini"
    gsettings set "$S" dock-items "['finder.dockitem','launchpad.dockitem','firefox.dockitem','mail.dockitem','system-settings.dockitem','terminal.dockitem','trash.dockitem']"
    mkdir -p "$HOME_DIR/.local/share/plank/dock1/launchers" \
             "$HOME_DIR/.config/plank/dock1/launchers"
    cp "$HOME_DIR/.config/plank/dock1/launchers/"*.dockitem \
       "$HOME_DIR/.local/share/plank/dock1/launchers/" 2>/dev/null || true
}

# ------------------------------------------------------------------ session
export HOME="$HOME_DIR"
export XDG_CONFIG_HOME="$HOME_DIR/.config"
export XDG_DATA_HOME="$HOME_DIR/.local/share"
export XDG_CACHE_HOME="$DEMO_ROOT/cache"
export XDG_DATA_DIRS="$PREFIX/usr/share:/usr/share"
export GDK_BACKEND=x11
unset WAYLAND_DISPLAY

# dedicated Xvfb (never the host display, never the test-suite :97)
if xwininfo -root -display "$DEMO_DISPLAY" >/dev/null 2>&1; then
    log "reusing live demo Xvfb on $DEMO_DISPLAY"
else
    Xvfb "$DEMO_DISPLAY" -screen 0 "$GEOMETRY" -nolisten tcp \
        >"$LOGS/xvfb.log" 2>&1 &
    XVFB_PID=$!
    for _ in $(seq 1 50); do
        xwininfo -root -display "$DEMO_DISPLAY" >/dev/null 2>&1 && break
        kill -0 "$XVFB_PID" 2>/dev/null || die "Xvfb died: $LOGS/xvfb.log"
        sleep 0.1
    done
    xwininfo -root -display "$DEMO_DISPLAY" >/dev/null 2>&1 \
        || die "Xvfb not ready"
    log "Xvfb up: $DEMO_DISPLAY ${GEOMETRY} pid=$XVFB_PID"
fi
export DISPLAY="$DEMO_DISPLAY"

PIDS=()
start() { # start <name> <logfile> <cmd...>
    local name="$1" lf="$2"; shift 2
    "$@" >>"$LOGS/$lf" 2>&1 &
    PIDS+=($!)
    log "started $name (pid $!)"
}

cleanup() {
    [ "${MV_DEMO_NO_CLEANUP:-0}" = "1" ] && return 0
    for p in "${PIDS[@]:-}"; do kill "$p" 2>/dev/null; done
    sleep 0.3
    for p in "${PIDS[@]:-}"; do kill -9 "$p" 2>/dev/null; done
    [ -n "${XVFB_PID:-}" ] && { kill "$XVFB_PID" 2>/dev/null; rm -f "/tmp/.X${DEMO_DISPLAY#*:}-lock"; }
    mv_gui_cleanup
}
trap cleanup EXIT INT TERM

# sweep: kill session components left over from a previous no-cleanup run —
# ONLY processes whose DISPLAY is the demo display (never host processes).
sweep_leftovers() {
    local p pid cmd
    for p in /proc/[0-9]*/environ; do
        pid="${p%/environ}"; pid="${pid#/proc/}"
        [ "$pid" = "$$" ] && continue
        tr '\0' '\n' <"$p" 2>/dev/null | grep -qx "DISPLAY=$DEMO_DISPLAY" || continue
        cmd="$(tr '\0' ' ' <"/proc/$pid/cmdline" 2>/dev/null)"
        case "$cmd" in
            *xfwm4*|*xfdesktop*|*xfce4-panel*|*plank*|*xfsettingsd*|*xfconfd*)
                kill "$pid" 2>/dev/null ;;
        esac
    done
    sleep 0.5
}

# session bus for xfconf/xfsettingsd/plank-dconf — ALWAYS a private bus:
# an inherited WSLg session bus would route xfconf/xsettings to the host
# session and the demo would render the host's config instead of the demo
# HOME's (observed: stock panel layout, no wallpaper, plugin dialog).
unset DBUS_SESSION_BUS_ADDRESS DBUS_SESSION_BUS_PID
eval "$(dbus-launch --sh-syntax 2>>"$LOGS/dbus.log")" || die "dbus-launch failed"
PIDS+=("$DBUS_SESSION_BUS_PID")
log "session bus: $DBUS_SESSION_BUS_ADDRESS"

sleep 0.5
sweep_leftovers
start xfconfd    xfconfd.log    xfconfd
sleep 1.0
start xfsettingsd xfsettingsd.log xfsettingsd
start xfwm4      xfwm4.log      xfwm4 --replace
# Wallpaper: xfdesktop 4.20.2 ignores its /backdrop xfconf properties in
# this headless Xvfb environment (verified: monitor0/monitorVNStr/connector
# property paths all fall back to the built-in default backdrop), so the
# wallpaper is set on the root window directly and xfdesktop is NOT started.
# Trade-off: no Home/Trash desktop icons in the demo shots.
feh --bg-fill "$PREFIX/usr/share/backgrounds/mavericks/mavericks-desktop.png" \
    >>"$LOGS/feh.log" 2>&1 || die "feh wallpaper failed (see $LOGS/feh.log)"
start panel      xfce4-panel.log xfce4-panel
seed_plank_dconf
start plank      plank.log      plank

# wait for the WM + desktop to be really there
for _ in $(seq 1 60); do
    if xprop -root -display "$DEMO_DISPLAY" _NET_SUPPORTING_WM_CHECK >/dev/null 2>&1 \
       && wmctrl -m >/dev/null 2>&1; then break; fi
    sleep 0.5
done
wmctrl -m || die "window manager did not come up (see $LOGS)"
log "session up: $(wmctrl -m | head -1)"

shot() { # shot <name>
    python3 "$REPO/scripts/demo/demo-capture.py" \
        --display "$DEMO_DISPLAY" --output "$SHOT_DIR/$1.png" || die "capture $1 failed"
}

# ------------------------------------------------------------- TEST CAPTURE
sleep 2
shot 00-session-test
log "test capture done: $SHOT_DIR/00-session-test.png"

# --------------------------------------------- app launch + shot sequence
MVBIN="$REPO/packages/mavericks-apps/src/mavericks-apps/bin"
MVLIB="$REPO/packages/mavericks-apps/src/mavericks-apps/lib"
ROFI_THEME_DIR="$PREFIX/usr/share/mavericks-apps"

runapp() { # runapp <binary-name> [args...]
    PYTHONPATH="$MVLIB" setsid "$MVBIN/$1" "${@:2}" >>"$LOGS/app-$1.log" 2>&1 &
}
wait_win() { # wait_win <title-substring> <timeout-sec>
    for _ in $(seq 1 $(("$2" * 4))); do
        wmctrl -l 2>/dev/null | grep -F "$1" >/dev/null 2>&1 && return 0
        sleep 0.25
    done
    log "WARN: window '$1' not seen in ${2}s"
    return 1
}
place() { # place <title-substring> <x> <y> <w> <h>
    wmctrl -r "$1" -b remove,maximized_vert,maximized_horz 2>/dev/null
    wmctrl -r "$1" -e "0,$2,$3,$4,$5" 2>/dev/null
}
close_all_apps() {
    wmctrl -l 2>/dev/null | awk '{$1=$2=$3=""; sub(/^ +/,""); print}' \
        | grep -vE '^$|MavLinOS Demo' >/dev/null 2>&1 || true
    for t in $(wmctrl -l 2>/dev/null | awk '{$1=$2=$3=""; sub(/^ +/,""); print}'); do
        wmctrl -c "$t" 2>/dev/null
    done
    sleep 1
}

log "opening apps for screenshots"
# --- Shot A: desktop with real apps -----------------------------------
thunar "$HOME_DIR/Documents" >>"$LOGS/app-finder.log" 2>&1 &
wait_win "Documents" 10 && place "Documents" 70 110 780 540
runapp mv-textedit "$HOME_DIR/Documents/Q4 Roadmap.txt"
wait_win "Q4 Roadmap" 10 && place "Q4 Roadmap" 900 150 600 460
runapp mv-calculator
wait_win "Calculator" 10 && place "Calculator" 1210 620 280 400
sleep 2
shot 01-desktop
log "shot A done"

# --- Shot B: Finder solo ----------------------------------------------
wmctrl -c "Q4 Roadmap" 2>/dev/null; wmctrl -c "Calculator" 2>/dev/null
sleep 1.5
place "Documents" 190 120 1300 810
sleep 1.5
shot 02-finder
log "shot B done"
wmctrl -c "Documents" 2>/dev/null
sleep 1

# --- Shot C: System Settings (+ About This Mac alternative) -----------
runapp mv-settings
wait_win "System Settings" 10 && place "System Settings" 460 210 760 520
sleep 1.5
shot 03-system-settings
log "shot C done"
wmctrl -c "System Settings" 2>/dev/null
sleep 1

runapp mv-about
wait_win "About This Mac" 10 && place "About This Mac" 490 220 700 500
sleep 1.5
shot 03b-about-this-mac
wmctrl -c "About This Mac" 2>/dev/null
sleep 1

# --- Shot D: Mission Control over real windows ------------------------
thunar "$HOME_DIR/Projects" >>"$LOGS/app-finder2.log" 2>&1 &
wait_win "Projects" 10 && place "Projects" 60 110 700 480
runapp mv-textedit "$HOME_DIR/Documents/MavLinOS Project Brief.md"
wait_win "MavLinOS Project Brief" 10 && place "MavLinOS Project Brief" 830 130 620 470
runapp mv-notes
wait_win "Notes" 10 && place "Notes" 180 620 420 330
runapp mv-calculator
wait_win "Calculator" 10 && place "Calculator" 1090 600 300 400
runapp mv-about
wait_win "About This Mac" 10 && place "About This Mac" 520 240 640 460
sleep 2
runapp mv-mc-gui
sleep 5
shot 04-mission-control
log "shot D done"
pkill -f 'mv-mc-gui' 2>/dev/null
sleep 1
close_all_apps

# --- Shot E: Launchpad (rofi, product command) ------------------------
DISPLAY="$DEMO_DISPLAY" setsid rofi -show -modi "launchpad:$MVBIN/mv-launchpad" \
    -theme "$ROFI_THEME_DIR/rofi-launchpad.rasi" >>"$LOGS/rofi-launchpad.log" 2>&1 &
sleep 4
shot 05-launchpad
pkill -x rofi 2>/dev/null
log "shot E done"

# --- Shot F candidate: Spotlight (rofi, product command) --------------
DISPLAY="$DEMO_DISPLAY" setsid rofi -show -modi "spotlight:$MVBIN/mv-spotlight" \
    -theme "$ROFI_THEME_DIR/rofi-mavericks.rasi" >>"$LOGS/rofi-spotlight.log" 2>&1 &
sleep 4
shot 05b-spotlight
pkill -x rofi 2>/dev/null
log "shot F candidate done"

log "ALL SHOTS in $SHOT_DIR"
if [ "${MV_DEMO_NO_CLEANUP:-0}" = "1" ]; then
    log "MV_DEMO_NO_CLEANUP=1 — session left running on $DEMO_DISPLAY for live probing"
    wait
fi
log "session left running for shot orchestration (this is the phase-1 harness)"
