PACKAGE_NAME="macbook12-audio-driver"
PACKAGE_VERSION="@PKGVER@"
BUILT_MODULE_NAME[0]="snd-hda-codec-cirrus"
DEST_MODULE_LOCATION[0]="kernel/sound/pci/hda"
AUTOINSTALL="yes"
MAKE[0]="make -C /usr/lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION} modules"
CLEAN="make -C /usr/lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION} clean"