# lightdm-gtk-greeter — Mavericks login screen
[greeter]
theme-name=Mavericks
icon-theme-name=Mavericks
cursor-theme-name=Mavericks-Cursors
cursor-theme-size=24
font-name=San Francisco 11
xft-antialias=true
xft-hintstyle=hintslight
xft-rgba=rgb
background=/usr/share/backgrounds/mavericks/mavericks-desktop.png
user-background=false
indicators=~host;~spacer;~clock;~spacer;~power;~a11y;~session;~language;~keyboard
clock-format=%a %-I:%M %p
screensaver-timeout=60
position=50%,center 50%,center
default-user-image=#avatar-default
hide-user-image=false
